### ISSUE TITLE
Can this project be run locally?

### ISSUE THREAD

**Issue by saraab-dev** [aramservices/Unimaginable-Python-Projects#1]
How can I run this project locally on my computer?

**Comment by aramb-dev** [comment]
Hello, @cat-35 

Yes this can be run locally, but it requires Python 3.9 installed. To get around that, [you could click this link for remotely running this program.](https://leancoding.co/join.php?id=OVCU33.html) [Also, make sure to look at this issue for more instructions!](https://github.com/aramservices198/Unimaginable-Python-Projects/issues/2)

**Comment by aramservices198** [comment]
#2
